- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.bashrc: bash/bashrc
    ~/.bash_profile: bash/profile
    ~/.config/git/config: git/config
    ~/.config/git/ignore_global: git/ignore
    ~/.config/geany/keybindings.conf: geany/keybindings.conf
    ~/.config/geany/filedefs: geany/filedefs
    ~/.config/ncmpcpp/config: ncmpcpp/config
    ~/.config/ncmpcpp/bindings: ncmpcpp/bindings
    ~/.config/polybar: polybar
    ~/.local/share/applications: ncmpcpp/ncmpcpp.desktop
    ~/.mpd/mpd.conf: mpd/mpd.conf
    ~/.config/mpDris2/mpDris2.conf: mpd/mpDris2.conf
    ~/.config/systemd/mpDris2.service: mpd/mpDris2.service
    ~/.profile: profile.sh
    ~/.ssh/config: ssh/config
    ~/.ssh/config.d/00_README: ssh/config.d/00_README
    ~/.ssh/config.d/99-git_wilcard.config: ssh/config.d/99-git_wilcard.config
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vimrc: vim/vimrc
    ~/.xinitrc: X11/xinitrc
    ~/.xprofile: X11/xprofile
    ~/.Xresources.src: X11/Xresources.src
    ~/.Xresources.d/urxvt: urxvt/Xresources
    ~/.config/user-dirs.dirs: X11/user-dirs.dirs
    ~/.config/awesome: awesome
    ~/.config/redshift.conf: redshift/redshift.conf

- create:
    ~/.ssh/keys/:
        mode: 0700

- shell:
    -
      command: ./bin/Xresources-preprocess
      description: Preprocess Xresources.src so that xrdb doesn't have to.
      stderr: true
    - [chmod 600 ./ssh/config, Ensure ./ssh/config only read/writable for owner]
#   - git submodules update # after linking ~/.gitconfig
