#!/bin/sh
#Standard Stuff
. /etc/X11/xinit/xinitrc-common
if [ -f $HOME/.Xclients ]; then
    exec $CK_XINIT_SESSION $SSH_AGENT $HOME/.Xclients || \
    exec $CK_XINIT_SESSION $SSH_AGENT $HOME/.Xclients
elif [ -f /etc/X11/xinit/Xclients ]; then
    exec $CK_XINIT_SESSION $SSH_AGENT /etc/X11/xinit/Xclients || \
    exec $CK_XINIT_SESSION $SSH_AGENT /etc/X11/xinit/Xclients
else
    # Failsafe settings.  Although we should never get here
    # (we provide fallbacks in Xclients as well) it can't hurt.
    [ -x /usr/bin/xsetroot ] && /usr/bin/xsetroot -solid '#222E45'
    [ -x /usr/bin/xclock ] && /usr/bin/xclock -geometry 100x100-5+5 &
    [ -x /usr/bin/xterm ] && xterm -geometry 80x50-50+150 &
    [ -x /usr/bin/twm ] && /usr/bin/twm
fi
# ---------------------------------------------------------------
#	 OWN
# ---------------------------------------------------------------

# Load Main Xresources
[ -f ~/.Xresources ] && xrdb -merge $HOME/.Xresources

# Load specific Xresources
XRESD="$HOME/.Xresources.d/"
for f in "$XRESD*"
do
	xrdb -merge "$f"
done

numlockx on # turn on numlock
setxkbmap -option caps:escape # caps lock works as escape


# Load session
DEFAULT_SESSION="awesome >> $HOME/.cache/awesome/stdout 2>> $HOME/.cache/awesome/stderr"
XTERM=xterm
case $1 in
	xfce4)
		RUN=startxfce4
		;;
	awesome)
		xscreensaver -nosplash &
		nm-applet &
		RUN=awesome
		;;
	enlightenment)
		RUN=enlightenment_start
		;;
	openbox)
		RUN=openbox
		;;
	cinnamon)
		RUN=cinnamon
		;;
	kde)
		RUN=startkde
		;;
	gnome)
		RUN=gnome-session
		;;
	unity)
		RUN=unity
		;;
	xterm)
		RUN=xterm
		;;
	*)
		RUN=$DEFAULT_SESSION
		;;
esac

exec "$RUN" || exec "$XTERM"
