" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin on

"Load LaTex-Suite on empty tex files
let g:tex_flavor='latex'

if &term=="xterm"
     set t_Co=8
     set t_Sb=^[[4%dm
     set t_Sf=^[[3%dm
endif

"Auto indentation, just "za" needed
filetype indent on

" Set tabbing stuff
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

" Show whitespace in characters (toggle with set list)
set listchars=tab:→\ ,space:·,nbsp:␣,trail:•,eol:¶,precedes:«,extends:»

"Folding
"augroup vimrc
"	au BufReadPre * setlocal foldmethod=indent
"	au BufWinEnter * if &fdm == 'indent' | setlocal foldmethod=manual | endif
"augroup END

" search for visually hightlighted text
vnoremap <c-f> y<ESC>/<c-r>"<CR>   

set grepprg=grep\ -nH\ $*

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"
